# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apiv2sdtxt2img_override_settings import Apiv2sdtxt2imgOverrideSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestApiv2sdtxt2imgOverrideSettings(unittest.TestCase):
    """Apiv2sdtxt2imgOverrideSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv2sdtxt2imgOverrideSettings(self):
        """Test Apiv2sdtxt2imgOverrideSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apiv2sdtxt2img_override_settings.Apiv2sdtxt2imgOverrideSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
