# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.image_api import ImageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = ImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_image_delete_post(self):
        """Test case for api_v2_image_delete_post

        Delete Image Information  # noqa: E501
        """
        pass

    def test_api_v2_image_feedbackinfo_post(self):
        """Test case for api_v2_image_feedbackinfo_post

        Update Image Feedback Information  # noqa: E501
        """
        pass

    def test_api_v2_image_get_post(self):
        """Test case for api_v2_image_get_post

        Get Image Information  # noqa: E501
        """
        pass

    def test_api_v2_image_getrequirement_post(self):
        """Test case for api_v2_image_getrequirement_post

        Get Project Requirement Information  # noqa: E501
        """
        pass

    def test_api_v2_image_list_post(self):
        """Test case for api_v2_image_list_post

        List Images in a Project  # noqa: E501
        """
        pass

    def test_api_v2_image_requirement_post(self):
        """Test case for api_v2_image_requirement_post

        Upload Project Requirement  # noqa: E501
        """
        pass

    def test_api_v2_image_upload_post(self):
        """Test case for api_v2_image_upload_post

        Upload Image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
