# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apiv2imagerequirement_request import Apiv2imagerequirementRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestApiv2imagerequirementRequest(unittest.TestCase):
    """Apiv2imagerequirementRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv2imagerequirementRequest(self):
        """Test Apiv2imagerequirementRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apiv2imagerequirement_request.Apiv2imagerequirementRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
