# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apiv2imagerequirement_request_requirement1 import Apiv2imagerequirementRequestRequirement1  # noqa: E501
from swagger_client.rest import ApiException


class TestApiv2imagerequirementRequestRequirement1(unittest.TestCase):
    """Apiv2imagerequirementRequestRequirement1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiv2imagerequirementRequestRequirement1(self):
        """Test Apiv2imagerequirementRequestRequirement1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apiv2imagerequirement_request_requirement1.Apiv2imagerequirementRequestRequirement1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
