# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.app_api_api import APPAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPPAPIApi(unittest.TestCase):
    """APPAPIApi unit test stubs"""

    def setUp(self):
        self.api = APPAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_download_image_origin_post(self):
        """Test case for api_v1_download_image_origin_post

        Download Original Image from S3  # noqa: E501
        """
        pass

    def test_api_v1_download_image_post(self):
        """Test case for api_v1_download_image_post

        Download Image After Inference  # noqa: E501
        """
        pass

    def test_api_v1_feedback_post(self):
        """Test case for api_v1_feedback_post

        Model Inference Feedback  # noqa: E501
        """
        pass

    def test_api_v1_get_model_list_post(self):
        """Test case for api_v1_get_model_list_post

        Get Model List from RDS and S3  # noqa: E501
        """
        pass

    def test_api_v1_get_model_post(self):
        """Test case for api_v1_get_model_post

        Download Model from RDS and S3  # noqa: E501
        """
        pass

    def test_api_v1_remote_inference_by_id_post(self):
        """Test case for api_v1_remote_inference_by_id_post

        Run Inference on Image by ID  # noqa: E501
        """
        pass

    def test_api_v1_style_transform_post(self):
        """Test case for api_v1_style_transform_post

        Style Transform for Image  # noqa: E501
        """
        pass

    def test_api_v1_upload_image_post(self):
        """Test case for api_v1_upload_image_post

        Upload Image for Inference or Dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
