# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.model_api import ModelApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_model_delete_post(self):
        """Test case for api_v2_model_delete_post

        Delete Model  # noqa: E501
        """
        pass

    def test_api_v2_model_download_post(self):
        """Test case for api_v2_model_download_post

        Download Model  # noqa: E501
        """
        pass

    def test_api_v2_model_get_post(self):
        """Test case for api_v2_model_get_post

        Get Model Information  # noqa: E501
        """
        pass

    def test_api_v2_model_list_post(self):
        """Test case for api_v2_model_list_post

        List Models  # noqa: E501
        """
        pass

    def test_api_v2_model_upload_post(self):
        """Test case for api_v2_model_upload_post

        Upload Model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
