# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auth_api import AuthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_auth_deleteuser_post(self):
        """Test case for api_v2_auth_deleteuser_post

        Delete User Account  # noqa: E501
        """
        pass

    def test_api_v2_auth_listuser_post(self):
        """Test case for api_v2_auth_listuser_post

        List All Users  # noqa: E501
        """
        pass

    def test_api_v2_auth_modifyuser_post(self):
        """Test case for api_v2_auth_modifyuser_post

        Modify User Information  # noqa: E501
        """
        pass

    def test_api_v2_auth_signin_post(self):
        """Test case for api_v2_auth_signin_post

        User Signin  # noqa: E501
        """
        pass

    def test_api_v2_auth_signup_post(self):
        """Test case for api_v2_auth_signup_post

        User Signup  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
