# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1_style_transform_body import V1StyleTransformBody  # noqa: E501
from swagger_client.rest import ApiException


class TestV1StyleTransformBody(unittest.TestCase):
    """V1StyleTransformBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1StyleTransformBody(self):
        """Test V1StyleTransformBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_style_transform_body.V1StyleTransformBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
