# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.project_api import ProjectApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_project_create_post(self):
        """Test case for api_v2_project_create_post

        Create Project  # noqa: E501
        """
        pass

    def test_api_v2_project_delete_post(self):
        """Test case for api_v2_project_delete_post

        Delete Project  # noqa: E501
        """
        pass

    def test_api_v2_project_get_post(self):
        """Test case for api_v2_project_get_post

        Get Single Project Information  # noqa: E501
        """
        pass

    def test_api_v2_project_list_post(self):
        """Test case for api_v2_project_list_post

        List All Projects From User Account  # noqa: E501
        """
        pass

    def test_api_v2_project_listall_post(self):
        """Test case for api_v2_project_listall_post

        List All Projects  # noqa: E501
        """
        pass

    def test_api_v2_project_update_post(self):
        """Test case for api_v2_project_update_post

        Update Project Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
