# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ec2context_stop_ec2_body import Ec2contextStopEc2Body  # noqa: E501
from swagger_client.rest import ApiException


class TestEc2contextStopEc2Body(unittest.TestCase):
    """Ec2contextStopEc2Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEc2contextStopEc2Body(self):
        """Test Ec2contextStopEc2Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ec2context_stop_ec2_body.Ec2contextStopEc2Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
