# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apiv2sdtxt2imgOverrideSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sd_model_checkpoint': 'str'
    }

    attribute_map = {
        'sd_model_checkpoint': 'sd_model_checkpoint'
    }

    def __init__(self, sd_model_checkpoint=None):  # noqa: E501
        """Apiv2sdtxt2imgOverrideSettings - a model defined in Swagger"""  # noqa: E501
        self._sd_model_checkpoint = None
        self.discriminator = None
        if sd_model_checkpoint is not None:
            self.sd_model_checkpoint = sd_model_checkpoint

    @property
    def sd_model_checkpoint(self):
        """Gets the sd_model_checkpoint of this Apiv2sdtxt2imgOverrideSettings.  # noqa: E501

        The checkpoint model to use for generation  # noqa: E501

        :return: The sd_model_checkpoint of this Apiv2sdtxt2imgOverrideSettings.  # noqa: E501
        :rtype: str
        """
        return self._sd_model_checkpoint

    @sd_model_checkpoint.setter
    def sd_model_checkpoint(self, sd_model_checkpoint):
        """Sets the sd_model_checkpoint of this Apiv2sdtxt2imgOverrideSettings.

        The checkpoint model to use for generation  # noqa: E501

        :param sd_model_checkpoint: The sd_model_checkpoint of this Apiv2sdtxt2imgOverrideSettings.  # noqa: E501
        :type: str
        """

        self._sd_model_checkpoint = sd_model_checkpoint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apiv2sdtxt2imgOverrideSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apiv2sdtxt2imgOverrideSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
