# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthSignupBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'firstname': 'str',
        'lastname': 'str',
        'email': 'str',
        'password': 'str',
        'password_check': 'str',
        'role': 'str'
    }

    attribute_map = {
        'firstname': 'firstname',
        'lastname': 'lastname',
        'email': 'email',
        'password': 'password',
        'password_check': 'password_check',
        'role': 'role'
    }

    def __init__(self, firstname=None, lastname=None, email=None, password=None, password_check=None, role=None):  # noqa: E501
        """AuthSignupBody - a model defined in Swagger"""  # noqa: E501
        self._firstname = None
        self._lastname = None
        self._email = None
        self._password = None
        self._password_check = None
        self._role = None
        self.discriminator = None
        if firstname is not None:
            self.firstname = firstname
        if lastname is not None:
            self.lastname = lastname
        if email is not None:
            self.email = email
        if password is not None:
            self.password = password
        if password_check is not None:
            self.password_check = password_check
        if role is not None:
            self.role = role

    @property
    def firstname(self):
        """Gets the firstname of this AuthSignupBody.  # noqa: E501


        :return: The firstname of this AuthSignupBody.  # noqa: E501
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this AuthSignupBody.


        :param firstname: The firstname of this AuthSignupBody.  # noqa: E501
        :type: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """Gets the lastname of this AuthSignupBody.  # noqa: E501


        :return: The lastname of this AuthSignupBody.  # noqa: E501
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this AuthSignupBody.


        :param lastname: The lastname of this AuthSignupBody.  # noqa: E501
        :type: str
        """

        self._lastname = lastname

    @property
    def email(self):
        """Gets the email of this AuthSignupBody.  # noqa: E501


        :return: The email of this AuthSignupBody.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AuthSignupBody.


        :param email: The email of this AuthSignupBody.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def password(self):
        """Gets the password of this AuthSignupBody.  # noqa: E501


        :return: The password of this AuthSignupBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthSignupBody.


        :param password: The password of this AuthSignupBody.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def password_check(self):
        """Gets the password_check of this AuthSignupBody.  # noqa: E501


        :return: The password_check of this AuthSignupBody.  # noqa: E501
        :rtype: str
        """
        return self._password_check

    @password_check.setter
    def password_check(self, password_check):
        """Sets the password_check of this AuthSignupBody.


        :param password_check: The password_check of this AuthSignupBody.  # noqa: E501
        :type: str
        """

        self._password_check = password_check

    @property
    def role(self):
        """Gets the role of this AuthSignupBody.  # noqa: E501


        :return: The role of this AuthSignupBody.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this AuthSignupBody.


        :param role: The role of this AuthSignupBody.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthSignupBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthSignupBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
