# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthModifyuserBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'role': 'str',
        'firstname': 'str',
        'lastname': 'str',
        'email': 'str',
        'password': 'str',
        'userid': 'int'
    }

    attribute_map = {
        'token': 'token',
        'role': 'role',
        'firstname': 'firstname',
        'lastname': 'lastname',
        'email': 'email',
        'password': 'password',
        'userid': 'userid'
    }

    def __init__(self, token=None, role=None, firstname=None, lastname=None, email=None, password=None, userid=None):  # noqa: E501
        """AuthModifyuserBody - a model defined in Swagger"""  # noqa: E501
        self._token = None
        self._role = None
        self._firstname = None
        self._lastname = None
        self._email = None
        self._password = None
        self._userid = None
        self.discriminator = None
        if token is not None:
            self.token = token
        if role is not None:
            self.role = role
        if firstname is not None:
            self.firstname = firstname
        if lastname is not None:
            self.lastname = lastname
        if email is not None:
            self.email = email
        if password is not None:
            self.password = password
        if userid is not None:
            self.userid = userid

    @property
    def token(self):
        """Gets the token of this AuthModifyuserBody.  # noqa: E501

        Access token to authenticate the request  # noqa: E501

        :return: The token of this AuthModifyuserBody.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this AuthModifyuserBody.

        Access token to authenticate the request  # noqa: E501

        :param token: The token of this AuthModifyuserBody.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def role(self):
        """Gets the role of this AuthModifyuserBody.  # noqa: E501

        User role  # noqa: E501

        :return: The role of this AuthModifyuserBody.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this AuthModifyuserBody.

        User role  # noqa: E501

        :param role: The role of this AuthModifyuserBody.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def firstname(self):
        """Gets the firstname of this AuthModifyuserBody.  # noqa: E501

        User's first name  # noqa: E501

        :return: The firstname of this AuthModifyuserBody.  # noqa: E501
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this AuthModifyuserBody.

        User's first name  # noqa: E501

        :param firstname: The firstname of this AuthModifyuserBody.  # noqa: E501
        :type: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """Gets the lastname of this AuthModifyuserBody.  # noqa: E501

        User's last name  # noqa: E501

        :return: The lastname of this AuthModifyuserBody.  # noqa: E501
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this AuthModifyuserBody.

        User's last name  # noqa: E501

        :param lastname: The lastname of this AuthModifyuserBody.  # noqa: E501
        :type: str
        """

        self._lastname = lastname

    @property
    def email(self):
        """Gets the email of this AuthModifyuserBody.  # noqa: E501

        User's email  # noqa: E501

        :return: The email of this AuthModifyuserBody.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AuthModifyuserBody.

        User's email  # noqa: E501

        :param email: The email of this AuthModifyuserBody.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def password(self):
        """Gets the password of this AuthModifyuserBody.  # noqa: E501

        User's password  # noqa: E501

        :return: The password of this AuthModifyuserBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthModifyuserBody.

        User's password  # noqa: E501

        :param password: The password of this AuthModifyuserBody.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def userid(self):
        """Gets the userid of this AuthModifyuserBody.  # noqa: E501

        User's ID to be modified  # noqa: E501

        :return: The userid of this AuthModifyuserBody.  # noqa: E501
        :rtype: int
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """Sets the userid of this AuthModifyuserBody.

        User's ID to be modified  # noqa: E501

        :param userid: The userid of this AuthModifyuserBody.  # noqa: E501
        :type: int
        """

        self._userid = userid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthModifyuserBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthModifyuserBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
