# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Ec2contextStartEc2Body(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'instance_id': 'str'
    }

    attribute_map = {
        'token': 'token',
        'instance_id': 'instance_id'
    }

    def __init__(self, token=None, instance_id=None):  # noqa: E501
        """Ec2contextStartEc2Body - a model defined in Swagger"""  # noqa: E501
        self._token = None
        self._instance_id = None
        self.discriminator = None
        if token is not None:
            self.token = token
        if instance_id is not None:
            self.instance_id = instance_id

    @property
    def token(self):
        """Gets the token of this Ec2contextStartEc2Body.  # noqa: E501

        Access token to authenticate the request  # noqa: E501

        :return: The token of this Ec2contextStartEc2Body.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Ec2contextStartEc2Body.

        Access token to authenticate the request  # noqa: E501

        :param token: The token of this Ec2contextStartEc2Body.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def instance_id(self):
        """Gets the instance_id of this Ec2contextStartEc2Body.  # noqa: E501

        The ID of the EC2 instance to be started  # noqa: E501

        :return: The instance_id of this Ec2contextStartEc2Body.  # noqa: E501
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this Ec2contextStartEc2Body.

        The ID of the EC2 instance to be started  # noqa: E501

        :param instance_id: The instance_id of this Ec2contextStartEc2Body.  # noqa: E501
        :type: str
        """

        self._instance_id = instance_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Ec2contextStartEc2Body, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ec2contextStartEc2Body):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
