# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectUpdateBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'username': 'str',
        'projectname': 'str',
        'status': 'str',
        'count': 'int',
        'quantity': 'int',
        'action': 'str'
    }

    attribute_map = {
        'token': 'token',
        'username': 'username',
        'projectname': 'projectname',
        'status': 'status',
        'count': 'count',
        'quantity': 'quantity',
        'action': 'action'
    }

    def __init__(self, token=None, username=None, projectname=None, status=None, count=None, quantity=None, action=None):  # noqa: E501
        """ProjectUpdateBody - a model defined in Swagger"""  # noqa: E501
        self._token = None
        self._username = None
        self._projectname = None
        self._status = None
        self._count = None
        self._quantity = None
        self._action = None
        self.discriminator = None
        if token is not None:
            self.token = token
        if username is not None:
            self.username = username
        if projectname is not None:
            self.projectname = projectname
        if status is not None:
            self.status = status
        if count is not None:
            self.count = count
        if quantity is not None:
            self.quantity = quantity
        if action is not None:
            self.action = action

    @property
    def token(self):
        """Gets the token of this ProjectUpdateBody.  # noqa: E501

        Access token to authenticate the request  # noqa: E501

        :return: The token of this ProjectUpdateBody.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this ProjectUpdateBody.

        Access token to authenticate the request  # noqa: E501

        :param token: The token of this ProjectUpdateBody.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def username(self):
        """Gets the username of this ProjectUpdateBody.  # noqa: E501

        User ID of the person attempting to update the project  # noqa: E501

        :return: The username of this ProjectUpdateBody.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ProjectUpdateBody.

        User ID of the person attempting to update the project  # noqa: E501

        :param username: The username of this ProjectUpdateBody.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def projectname(self):
        """Gets the projectname of this ProjectUpdateBody.  # noqa: E501

        Name of the project to be updated  # noqa: E501

        :return: The projectname of this ProjectUpdateBody.  # noqa: E501
        :rtype: str
        """
        return self._projectname

    @projectname.setter
    def projectname(self, projectname):
        """Sets the projectname of this ProjectUpdateBody.

        Name of the project to be updated  # noqa: E501

        :param projectname: The projectname of this ProjectUpdateBody.  # noqa: E501
        :type: str
        """

        self._projectname = projectname

    @property
    def status(self):
        """Gets the status of this ProjectUpdateBody.  # noqa: E501

        New status of the project, used when action is 'confirm_status'  # noqa: E501

        :return: The status of this ProjectUpdateBody.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProjectUpdateBody.

        New status of the project, used when action is 'confirm_status'  # noqa: E501

        :param status: The status of this ProjectUpdateBody.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def count(self):
        """Gets the count of this ProjectUpdateBody.  # noqa: E501

        The new remaining count for image generation, used when action is 'modify_remain_count'  # noqa: E501

        :return: The count of this ProjectUpdateBody.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this ProjectUpdateBody.

        The new remaining count for image generation, used when action is 'modify_remain_count'  # noqa: E501

        :param count: The count of this ProjectUpdateBody.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def quantity(self):
        """Gets the quantity of this ProjectUpdateBody.  # noqa: E501

        The new image quantity, used when action is 'modify_img_quantity'  # noqa: E501

        :return: The quantity of this ProjectUpdateBody.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ProjectUpdateBody.

        The new image quantity, used when action is 'modify_img_quantity'  # noqa: E501

        :param quantity: The quantity of this ProjectUpdateBody.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def action(self):
        """Gets the action of this ProjectUpdateBody.  # noqa: E501

        The type of update action to perform. Possible values 'confirm_status', 'modify_remain_count', 'modify_img_quantity'  # noqa: E501

        :return: The action of this ProjectUpdateBody.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this ProjectUpdateBody.

        The type of update action to perform. Possible values 'confirm_status', 'modify_remain_count', 'modify_img_quantity'  # noqa: E501

        :param action: The action of this ProjectUpdateBody.  # noqa: E501
        :type: str
        """

        self._action = action

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectUpdateBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectUpdateBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
