# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1RemoteInferenceByIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token': 'str',
        'image_id': 'str',
        'model_type': 'str',
        'model_name': 'str'
    }

    attribute_map = {
        'access_token': 'access_token',
        'image_id': 'image_id',
        'model_type': 'modelType',
        'model_name': 'modelName'
    }

    def __init__(self, access_token=None, image_id=None, model_type=None, model_name=None):  # noqa: E501
        """V1RemoteInferenceByIdBody - a model defined in Swagger"""  # noqa: E501
        self._access_token = None
        self._image_id = None
        self._model_type = None
        self._model_name = None
        self.discriminator = None
        if access_token is not None:
            self.access_token = access_token
        if image_id is not None:
            self.image_id = image_id
        if model_type is not None:
            self.model_type = model_type
        if model_name is not None:
            self.model_name = model_name

    @property
    def access_token(self):
        """Gets the access_token of this V1RemoteInferenceByIdBody.  # noqa: E501

        Access token to authenticate the request  # noqa: E501

        :return: The access_token of this V1RemoteInferenceByIdBody.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this V1RemoteInferenceByIdBody.

        Access token to authenticate the request  # noqa: E501

        :param access_token: The access_token of this V1RemoteInferenceByIdBody.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def image_id(self):
        """Gets the image_id of this V1RemoteInferenceByIdBody.  # noqa: E501

        The ID of the image on which inference is to be run  # noqa: E501

        :return: The image_id of this V1RemoteInferenceByIdBody.  # noqa: E501
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id):
        """Sets the image_id of this V1RemoteInferenceByIdBody.

        The ID of the image on which inference is to be run  # noqa: E501

        :param image_id: The image_id of this V1RemoteInferenceByIdBody.  # noqa: E501
        :type: str
        """

        self._image_id = image_id

    @property
    def model_type(self):
        """Gets the model_type of this V1RemoteInferenceByIdBody.  # noqa: E501

        The type of model to be used for inference (e.g., \"yolov5\", \"yolov3\", \"yolov3-tiny\")  # noqa: E501

        :return: The model_type of this V1RemoteInferenceByIdBody.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this V1RemoteInferenceByIdBody.

        The type of model to be used for inference (e.g., \"yolov5\", \"yolov3\", \"yolov3-tiny\")  # noqa: E501

        :param model_type: The model_type of this V1RemoteInferenceByIdBody.  # noqa: E501
        :type: str
        """

        self._model_type = model_type

    @property
    def model_name(self):
        """Gets the model_name of this V1RemoteInferenceByIdBody.  # noqa: E501

        The name of the model used for inference  # noqa: E501

        :return: The model_name of this V1RemoteInferenceByIdBody.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this V1RemoteInferenceByIdBody.

        The name of the model used for inference  # noqa: E501

        :param model_name: The model_name of this V1RemoteInferenceByIdBody.  # noqa: E501
        :type: str
        """

        self._model_name = model_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1RemoteInferenceByIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1RemoteInferenceByIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
