# coding: utf-8

"""
    BE v2 API

    API documentation for BE v2, handling authentication, project management, image operations, model management, and EC2 context.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1StyleTransformBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token': 'str',
        'file': 'str',
        'transform_style': 'str',
        'device_info': 'str'
    }

    attribute_map = {
        'access_token': 'access_token',
        'file': 'file',
        'transform_style': 'transform_style',
        'device_info': 'DeviceInfo'
    }

    def __init__(self, access_token=None, file=None, transform_style=None, device_info=None):  # noqa: E501
        """V1StyleTransformBody - a model defined in Swagger"""  # noqa: E501
        self._access_token = None
        self._file = None
        self._transform_style = None
        self._device_info = None
        self.discriminator = None
        if access_token is not None:
            self.access_token = access_token
        if file is not None:
            self.file = file
        if transform_style is not None:
            self.transform_style = transform_style
        if device_info is not None:
            self.device_info = device_info

    @property
    def access_token(self):
        """Gets the access_token of this V1StyleTransformBody.  # noqa: E501

        Access token to authenticate the request  # noqa: E501

        :return: The access_token of this V1StyleTransformBody.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this V1StyleTransformBody.

        Access token to authenticate the request  # noqa: E501

        :param access_token: The access_token of this V1StyleTransformBody.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def file(self):
        """Gets the file of this V1StyleTransformBody.  # noqa: E501

        The image file to be uploaded and transformed  # noqa: E501

        :return: The file of this V1StyleTransformBody.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this V1StyleTransformBody.

        The image file to be uploaded and transformed  # noqa: E501

        :param file: The file of this V1StyleTransformBody.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def transform_style(self):
        """Gets the transform_style of this V1StyleTransformBody.  # noqa: E501

        The style to transform the image into (e.g., \"Pixart\" or \"RealTek\")  # noqa: E501

        :return: The transform_style of this V1StyleTransformBody.  # noqa: E501
        :rtype: str
        """
        return self._transform_style

    @transform_style.setter
    def transform_style(self, transform_style):
        """Sets the transform_style of this V1StyleTransformBody.

        The style to transform the image into (e.g., \"Pixart\" or \"RealTek\")  # noqa: E501

        :param transform_style: The transform_style of this V1StyleTransformBody.  # noqa: E501
        :type: str
        """

        self._transform_style = transform_style

    @property
    def device_info(self):
        """Gets the device_info of this V1StyleTransformBody.  # noqa: E501

        Information about the device used to capture the image (e.g., \"samsung s24\")  # noqa: E501

        :return: The device_info of this V1StyleTransformBody.  # noqa: E501
        :rtype: str
        """
        return self._device_info

    @device_info.setter
    def device_info(self, device_info):
        """Sets the device_info of this V1StyleTransformBody.

        Information about the device used to capture the image (e.g., \"samsung s24\")  # noqa: E501

        :param device_info: The device_info of this V1StyleTransformBody.  # noqa: E501
        :type: str
        """

        self._device_info = device_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1StyleTransformBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1StyleTransformBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
